# public specification
print_freq: 100
save_freq: 40
batch_size: 64
num_workers: 4

# optimization and training
epochs: 240
init_epochs: 30
learning_rate: 0.05
lr_decay_epochs: '150,180,210'
lr_decay_rate: 0.1
weight_decay: 5e-4
momentum: 0.9

# data
dataset: 'cifar100'   # ['cifar100', 'tinyimagenet']
data_dir: './data/cifar100'   # your data directory

# model
model_s: 'ShuffleV2'
model_t: 'resnet32x4'
path_t: './save/teacher_model/cifar100/resnet32x4_vanilla.pth'    # the teacher model path
save_folder: './save/student_model/cifar100/ours/res32x4_shufflenetv2'

# kd
distill: 'ASKD'
gamma: 1  # task loss weight
alpha: 0  # hkd loss weight
beta: 1   # kd loss weight
kd_T: 4   # the temperature


group: "res_last"   # distillation position

# region
w_rs: 5   # the regional similarity loss weight
r: 4    # the division factor

# class
w_cs: 14    # the class similarity loss weight
