# public specification
print_freq: 100
save_freq: 40
batch_size: 64
num_workers: 4

# optimization and training
epochs: 240
init_epochs: 30
learning_rate: 0.05
lr_decay_epochs: '150,180,210'
lr_decay_rate: 0.1
weight_decay: 5e-4
momentum: 0.9

# data
dataset: 'cifar100'
data_dir: './data/cifar100'

# model
model_s: 'MobileNetV2'
model_t: 'ResNet50'
path_t: './save/teacher_model/cifar100/ResNet50_vanilla.pth'
save_folder: './save/student_model/cifar100/rkd/res50_mobilenetv2'

# kd
distill: 'rkd'
gamma: 1  # task
alpha: 0  # hkd
beta: 1   # kd
kd_T: 4   # temperature

